# Generated by Django 5.0.3 on 2025-03-11 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile_model',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
