# Generated by Django 5.0.3 on 2025-03-11 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0002_alter_userprofile_model_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile_model',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
