# Generated by Django 5.0.3 on 2025-03-11 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0004_services_model_provider_services_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider_services_model',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admins.services_model'),
        ),
    ]
