# Generated by Django 5.0.3 on 2025-03-12 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0005_provider_services_model_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider_services_model',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
