# Generated by Django 5.0.3 on 2025-03-13 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0008_complaint_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile_model',
            name='phone_number',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
